import streamlit as st
import streamlit.components.v1 as components
import json

def display_coloring_game(emotion, key_prefix="color_game"):
    """
    A high-performance interactive coloring game where all logic is handled 
    in the frontend to prevent jarring Streamlit refreshes.
    """
    st.subheader("🎨 Instant Color Therapy")

    # Define the palette types
    palette_types = {
        "Ocean Calm": ["#03045e", "#0077b6", "#00b4d8", "#48cae4", "#90e0ef", "#ade8f4", "#caf0f8", "#ffffff"],
        "Sunset Energy": ["#ff0000", "#ff4d6d", "#c9184a", "#ff758f", "#ff8fa3", "#ffb703", "#fb8500", "#ffffff"],
        "Forest Grounding": ["#081c15", "#1b4332", "#2d6a4f", "#40916c", "#52b788", "#74c69d", "#95d5b2", "#ffffff"],
        "Royal Mystery": ["#10002b", "#240046", "#3c096c", "#5a189a", "#7b2cbf", "#9d4edd", "#c77dff", "#ffffff"],
        "Soft Pastel": ["#cdb4db", "#ffc8dd", "#ffafcc", "#bde0fe", "#a2d2ff", "#fde2e4", "#fad2e1", "#ffffff"]
    }

    # Default settings based on emotion
    emotion_map = {
        "sad": "Ocean Calm", 
        "happy": "Sunset Energy", 
        "fear": "Forest Grounding", 
        "anger": "Royal Mystery", 
        "neutral": "Soft Pastel",
        "disgust": "Forest Grounding",
        "surprise": "Sunset Energy",
        "contempt": "Royal Mystery"
    }
    initial_palette_name = emotion_map.get(emotion.lower(), "Soft Pastel")
    
    # Designs and their SVG bodies
    designs = {
        "Concentric": '''
            <rect class="region" x="50" y="50" width="300" height="300" fill="#FFF" stroke="#333" stroke-width="3"/>
            <rect class="region" x="100" y="100" width="200" height="200" fill="#FFF" stroke="#333" stroke-width="3"/>
            <rect class="region" x="150" y="150" width="100" height="100" fill="#FFF" stroke="#333" stroke-width="3"/>
            <circle class="region" cx="200" cy="200" r="40" fill="#FFF" stroke="#333" stroke-width="3"/>
        ''',
        "Geometric Grid": '''
            <rect class="region" x="50" y="50" width="150" height="150" fill="#FFF" stroke="#333" stroke-width="3"/>
            <rect class="region" x="200" y="50" width="150" height="150" fill="#FFF" stroke="#333" stroke-width="3"/>
            <rect class="region" x="50" y="200" width="150" height="150" fill="#FFF" stroke="#333" stroke-width="3"/>
            <rect class="region" x="200" y="200" width="150" height="150" fill="#FFF" stroke="#333" stroke-width="3"/>
            <circle class="region" cx="200" cy="200" r="60" fill="#FFF" stroke="#333" stroke-width="2"/>
        ''',
        "Diamond Cross": '''
            <polygon class="region" points="200,50 350,200 200,200 50,200" fill="#FFF" stroke="#333" stroke-width="3"/>
            <polygon class="region" points="200,350 350,200 200,200 50,200" fill="#FFF" stroke="#333" stroke-width="3"/>
            <polygon class="region" points="50,200 200,50 200,200 200,350" fill="#FFF" stroke="#333" stroke-width="3"/>
            <polygon class="region" points="350,200 200,50 200,200 200,350" fill="#FFF" stroke="#333" stroke-width="3"/>
        ''',
        "Flower Petals": '''
            <ellipse class="region" cx="200" cy="120" rx="40" ry="70" fill="#FFF" stroke="#333" stroke-width="3" transform="rotate(0, 200, 200)"/>
            <ellipse class="region" cx="200" cy="120" rx="40" ry="70" fill="#FFF" stroke="#333" stroke-width="3" transform="rotate(90, 200, 200)"/>
            <ellipse class="region" cx="200" cy="120" rx="40" ry="70" fill="#FFF" stroke="#333" stroke-width="3" transform="rotate(180, 200, 200)"/>
            <ellipse class="region" cx="200" cy="120" rx="40" ry="70" fill="#FFF" stroke="#333" stroke-width="3" transform="rotate(270, 200, 200)"/>
            <circle class="region" cx="200" cy="200" r="30" fill="#FFF" stroke="#333" stroke-width="2" opacity="0.8"/>
        '''
    }

    # Serialize data for JS
    palette_json = json.dumps(palette_types)
    designs_json = json.dumps(designs)

    html_code = f"""
    <div id="coloring-game-container" style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; color: #333; background: #fff; padding: 20px; border-radius: 15px; box-shadow: 0 4px 12px rgba(0,0,0,0.1); border: 1px solid #eee;">
        
        <!-- Design Selection -->
        <div style="margin-bottom: 20px;">
            <label style="font-weight: bold; display: block; margin-bottom: 10px; font-size: 1.1em;">🖼️ 1. Choose a Design</label>
            <div id="design-buttons" style="display: flex; gap: 10px; flex-wrap: wrap;">
                <!-- Generated by JS -->
            </div>
        </div>

        <!-- Palette Selection -->
        <div style="margin-bottom: 20px;">
            <label style="font-weight: bold; display: block; margin-bottom: 10px; font-size: 1.1em;">🌈 2. Select a Palette</label>
            <div id="palette-buttons" style="display: flex; gap: 10px; flex-wrap: wrap;">
                <!-- Generated by JS -->
            </div>
        </div>

        <div style="display: flex; gap: 30px; flex-wrap: wrap; align-items: flex-start;">
            <!-- Color Picker -->
            <div style="flex: 1; min-width: 200px;">
                <label style="font-weight: bold; display: block; margin-bottom: 10px; font-size: 1.1em;">🎨 3. Pick a Color</label>
                <div id="color-grid" style="display: grid; grid-template-columns: repeat(4, 1fr); gap: 10px; margin-bottom: 20px;">
                    <!-- Generated by JS -->
                </div>
                <div style="padding: 15px; background: #f8f9fa; border-radius: 10px; border: 1px solid #ddd; text-align: center;">
                    <div style="font-size: 0.9em; margin-bottom: 8px; color: #666;">Active Brush</div>
                    <div id="active-brush" style="width: 40px; height: 40px; border-radius: 50%; border: 3px solid #333; margin: 0 auto; background: #fff; transition: background 0.3s;"></div>
                </div>
                <button id="clear-btn" style="width: 100%; margin-top: 20px; padding: 12px; background: #ff4b4b; color: white; border: none; border-radius: 8px; font-weight: bold; cursor: pointer; transition: 0.3s;">
                    🔄 Clear Canvas
                </button>
            </div>

            <!-- Canvas -->
            <div style="flex: 2; min-width: 300px; text-align: center;">
                <div id="canvas-holder" style="background: #fafafa; padding: 15px; border-radius: 15px; border: 2px solid #333; display: inline-block;">
                    <svg id="coloring-svg" width="400" height="400" viewBox="0 0 400 400" style="cursor: crosshair; display: block;">
                        <!-- SVG Body injected here -->
                    </svg>
                    <div id="design-label" style="margin-top: 10px; color: #999; font-size: 0.8em; font-weight: bold; text-transform: uppercase;"></div>
                </div>
                <p style="color: #666; font-size: 0.9em; margin-top: 10px;">✨ Click regions on the canvas to apply color</p>
            </div>
        </div>
    </div>

    <script>
        const palettes = {palette_json};
        const designs = {designs_json};
        let currentPaletteName = "{initial_palette_name}";
        let currentDesignName = "Concentric";
        let activeColor = palettes[currentPaletteName][0];

        // UI Elements
        const designButtonsContainer = document.getElementById('design-buttons');
        const paletteButtonsContainer = document.getElementById('palette-buttons');
        const colorGrid = document.getElementById('color-grid');
        const activeBrush = document.getElementById('active-brush');
        const svgElement = document.getElementById('coloring-svg');
        const designLabel = document.getElementById('design-label');
        const clearBtn = document.getElementById('clear-btn');

        function init() {{
            renderDesignButtons();
            renderPaletteButtons();
            renderColorGrid();
            setDesign(currentDesignName);
            setActiveColor(activeColor);
        }}

        function renderDesignButtons() {{
            designButtonsContainer.innerHTML = '';
            Object.keys(designs).forEach(name => {{
                const btn = document.createElement('button');
                btn.innerText = name;
                styleButton(btn, name === currentDesignName);
                btn.onclick = () => setDesign(name);
                designButtonsContainer.appendChild(btn);
            }});
        }}

        function renderPaletteButtons() {{
            paletteButtonsContainer.innerHTML = '';
            Object.keys(palettes).forEach(name => {{
                const btn = document.createElement('button');
                btn.innerText = name;
                styleButton(btn, name === currentPaletteName);
                btn.onclick = () => setPalette(name);
                paletteButtonsContainer.appendChild(btn);
            }});
        }}

        function styleButton(btn, isActive) {{
            btn.style.padding = '8px 15px';
            btn.style.border = '2px solid ' + (isActive ? '#007bff' : '#ddd');
            btn.style.borderRadius = '20px';
            btn.style.background = isActive ? '#007bff' : '#fff';
            btn.style.color = isActive ? '#fff' : '#333';
            btn.style.cursor = 'pointer';
            btn.style.fontWeight = 'bold';
            btn.style.fontSize = '0.85em';
            btn.style.transition = '0.2s';
        }}

        function renderColorGrid() {{
            colorGrid.innerHTML = '';
            palettes[currentPaletteName].forEach(color => {{
                const item = document.createElement('div');
                item.style.backgroundColor = color;
                item.style.height = '35px';
                item.style.borderRadius = '6px';
                item.style.border = '2px solid #ddd';
                item.style.cursor = 'pointer';
                if (color === activeColor) item.style.borderColor = '#333';
                item.onclick = () => setActiveColor(color);
                colorGrid.appendChild(item);
            }});
        }}

        function setDesign(name) {{
            currentDesignName = name;
            svgElement.innerHTML = designs[name];
            designLabel.innerText = name + " Canvas";
            renderDesignButtons();
            attachRegionEvents();
        }}

        function setPalette(name) {{
            currentPaletteName = name;
            renderPaletteButtons();
            renderColorGrid();
            // Optional: set active color to first of new palette
            setActiveColor(palettes[name][0]);
        }}

        function setActiveColor(color) {{
            activeColor = color;
            activeBrush.style.backgroundColor = color;
            // Update selection in grid
            Array.from(colorGrid.children).forEach(child => {{
                child.style.borderColor = (child.style.backgroundColor === hexToRgb(color)) ? '#333' : '#ddd';
            }});
        }}

        function hexToRgb(hex) {{
            var result = /^#?([a-f\d]{{2}})([a-f\d]{{2}})([a-f\d]{{2}})$/i.exec(hex);
            return result ? "rgb(" + parseInt(result[1], 16) + ", " + parseInt(result[2], 16) + ", " + parseInt(result[3], 16) + ")" : null;
        }}

        function attachRegionEvents() {{
            const regions = svgElement.querySelectorAll('.region');
            regions.forEach(region => {{
                region.addEventListener('click', function() {{
                    this.setAttribute('fill', activeColor);
                    this.style.transition = 'fill 0.3s ease';
                }});
                region.addEventListener('mouseover', function() {{
                    this.style.opacity = '0.7';
                }});
                region.addEventListener('mouseout', function() {{
                    this.style.opacity = '1';
                }});
            }});
        }}

        clearBtn.onclick = () => {{
            svgElement.querySelectorAll('.region').forEach(r => r.setAttribute('fill', '#FFFFFF'));
        }};

        clearBtn.onmouseover = () => clearBtn.style.background = '#ff3333';
        clearBtn.onmouseout = () => clearBtn.style.background = '#ff4b4b';

        init();
    </script>
    """
    components.html(html_code, height=650)
    st.success("✨ **Tip:** All controls are instant! Switching designs or palettes won't refresh the page.")

